### ISSUE TITLE
ConvertToEnum fails with composite words (in geojson)

### ISSUE THREAD

**Issue by kluiverjh** [brnkhy/MapzenGo#34]
The ConvertToEnum in class Extensions throws sometimes an exception. The problem is with composite words in the enum name.

E.g. 
The enum definition LanduseKind has enum "RecreationGround" but geojson returns "Recreation_Ground".

The easy way is to remove the "_" from the string before converting.

Every exception is a large performance penalty!

**Comment by brnkhy** [comment]
I'm sure I fixed this (today) but probably not pushed yet. It was a silly mistake, I used resharper renaming too to fix first letters of those enums (wasn't capitalized), turns out it also removed underscores. I'll push it soon. I havent checked (god knows why) other enums yet though, they probably have the same error as well.

**Comment by brnkhy** [comment]
just fixed bunch of other enums as well. couldnt fix buildingtype though, I don't have a proper list of those as Roman submitted those. I'll check them later as well. pushed fixed enums on dev branch
