### ISSUE TITLE
Buildings being seperate gameobject and not a single mesh causing performance issues

### ISSUE THREAD

**Issue by brnkhy** [brnkhy/MapzenGo#8]

**Comment by heath3n** [comment]
I'm not too familiar with the visual aspects of Unity but are the separate building components retained in memory anywhere (imagine grouping objects in an image editor) or do they permanently become one big mesh?

I ask because some games might want to utilize certain buildings as features. I suppose we can always simply get the world coordinates of a tap, convert it back to TSM coordinates, and check the JSON to see if there's a building there, but it seems like that still limits visual changes we can make to any buildings unless we redraw a new object over the existing one.

It's hardly the most pressing issue, but it's something to consider for the future.

**Comment by brnkhy** [comment]
I totally agree with that. My initial plan was (actually still is) to make buildings separate object and then maybe detail them even further. This was player will be able to select, click, choose whatever, that object easily.
But the problem is, gameobjects aren't free. They come with at least 2-3 components and require additional draw calls. You can use shared material and make them static to reduce draw calls and improve performance but still, merging them into one big mesh will be much better for mobile for example (assuming you don't need direct interaction, i.e. pokemon go).
I'll make that as an alternative building factory so you'll be able to switch whichever you want.

**Comment by brnkhy** [comment]
I actually just realized that I skipped your question; all buildings are kept in a list inside BuildingFactory. You can query anything from there. Let me know if I missed something again ;)

**Comment by heath3n** [comment]
Ha, no worries; I've actually been working my way through a [nice tutorial](http://catlikecoding.com/unity/tutorials/hex-map-1/) on making a hexagonal grid that covers mesh-making, edge blending, individual selection, etc.

**Comment by brnkhy** [comment]
somewhat completed in 0bf25143a3fe87c92d9a48610cb72fa40e35c9ed
